let name = prompt("ismingizni  kiriting... ")
let surname = prompt("familyangizni kiriting... ")
let age = prompt("yoshingizni kiriting... ")
let from = prompt("yashash  joyingizni  kiriting... ")
let job = prompt("qayerda  ishlaysiz  ? ")
let student = prompt("o'qiysizmi o'qimaysizmi  agar o'qisez talabaman  deb yozing  o'qimasez  yo'q deb  yozing")
let launguage = prompt("chet qilini bilasmiz ?")
let hobby = prompt("hobbyiz  nima ? ")
let interest = prompt("dasturlashga qiziqasizmi ? ")   
let dream = prompt("orzuingiz nima ? ")
let year = prompt("tug'ulgan yilinggizni kiriting... ")
let moon = prompt("tug'ulgan oyinggizni kiriting.. ")
let day = prompt("tug'ulgan kuningizni  kiriting.. ")
let email = prompt("emailingizni kiriting...")
let phone = prompt("qandey rusumdagi telefon ishlatasiz ?")
let quiz = prompt("18 / 2 =")



console.log('sizning  ismingiz: ' + name)
console.log('sizning  familyangiz: ' + surname)
console.log('sizning  yoshingiz: ' + age)
console.log('sizning  yashash manzilingiz: ' + from)
console.log('sizning  kasbingiz: ' + job)
console.log('siz  talabamisiz : ' + student)
console.log('sizning  chet tilini  bilishiz: ' + launguage)
console.log('sizning  hobbyingiz: ' + hobby)
console.log('sizni  dasturlashga bulgan qiziqishiz : ' + interest)
console.log('sizning  orzuingiz: ' + dream)
console.log("sizning  tug'ulgan yil oy kuningiz: " + year + moon + day)
console.log('sizning  emailinggiz: ' + email)
console.log('sizning  telefoniiz modeli: ' + phone)
console.log('javob: ' + quiz)